import { HypeCheckReport } from '@/lib/types'
import ReportHeader from './ReportHeader'
import MarketOpportunity from './MarketOpportunity'
import CompetitiveLandscape from './CompetitiveLandscape'
import DemandSignals from './DemandSignals'
import MonetisationViability from './MonetisationViability'
import ExecutionRisk from './ExecutionRisk'
import NextStep from './NextStep'

export default function ReportView({ report }: { report: HypeCheckReport }) {
  return (
    <>
      <ReportHeader
        ideaTitle={report.ideaTitle}
        hypeScore={report.hypeScore}
        verdict={report.verdict}
        oneLinerSummary={report.oneLinerSummary}
      />
      <MarketOpportunity
        metrics={report.marketOpportunity.metrics}
      />
      <CompetitiveLandscape
        competitors={report.competitiveLandscape.competitors}
        competitiveAdvantage={report.competitiveLandscape.competitiveAdvantage}
      />
      <DemandSignals
        signals={report.demandSignals.signals}
        overallDemandStrength={report.demandSignals.overallDemandStrength}
      />
      <MonetisationViability
        score={report.monetisationViability.score}
        recommendedModel={report.monetisationViability.recommendedModel}
        pricingSuggestion={report.monetisationViability.pricingSuggestion}
        keyRisk={report.monetisationViability.keyRisk}
      />
      <ExecutionRisk
        factors={report.executionRisk.factors}
        overallRiskLevel={report.executionRisk.overallRiskLevel}
      />
      <NextStep
        action={report.nextStep.action}
        rationale={report.nextStep.rationale}
      />
      <p className="pb-8 pt-4 text-center text-[12px] text-[#555555]">
        Generated by{' '}
        <span className="text-[#7C3AED]">HypeCheck</span> · NullHype AI
      </p>
    </>
  )
}
